server:
  port: 8090
spring:
  application:
    name: department-service
  cloud:
    config:
      uri: http://localhost:8070

  datasource:
    url: jdbc:mysql://localhost:3306/group7
    username: prabhat
    password: prabhat

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

  security:
    user:
      name: admin
      password: Test@123

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
